---
title: "CKD.Analysis"
author: "Shuai Guo"
date: "`r Sys.Date()`"
output: html_document
---
```{r warning=FALSE, message=FALSE}
library(dplyr)
library(Seurat)
library(patchwork)
library(ggplot2)
```

```{r fig.height=4, fig.width=5.5}
ckd_data = Read10X(data.dir = "../raw_UMI_counts/RTN3KO1/")
ckd_ko1 = CreateSeuratObject(counts = ckd_data, project = "CKD.KO1", min.cells = 10, min.features = 200)
ckd_ko1[["percent.mt"]] = PercentageFeatureSet(ckd_ko1, pattern = "^mt-")

ckd_data = Read10X(data.dir = "../raw_UMI_counts/RTN3KO2/")
ckd_ko2 = CreateSeuratObject(counts = ckd_data, project = "CKD.KO2", min.cells = 10, min.features = 200)
ckd_ko2[["percent.mt"]] = PercentageFeatureSet(ckd_ko2, pattern = "^mt-")

ckd_data = Read10X(data.dir = "../raw_UMI_counts/RTN3KO3/")
ckd_ko3 = CreateSeuratObject(counts = ckd_data, project = "CKD.KO3", min.cells = 10, min.features = 200)
ckd_ko3[["percent.mt"]] = PercentageFeatureSet(ckd_ko3, pattern = "^mt-")

ckd_data = Read10X(data.dir = "../raw_UMI_counts/WT1/")
ckd_wt1 = CreateSeuratObject(counts = ckd_data, project = "CKD.WT1", min.cells = 10, min.features = 200)
ckd_wt1[["percent.mt"]] = PercentageFeatureSet(ckd_wt1, pattern = "^mt-")

ckd_data = Read10X(data.dir = "../raw_UMI_counts/WT2/")
ckd_wt2 = CreateSeuratObject(counts = ckd_data, project = "CKD.WT2", min.cells = 10, min.features = 200)
ckd_wt2[["percent.mt"]] = PercentageFeatureSet(ckd_wt2, pattern = "^mt-")

ckd_data = Read10X(data.dir = "../raw_UMI_counts/WT3/")
ckd_wt3 = CreateSeuratObject(counts = ckd_data, project = "CKD.WT3", min.cells = 10, min.features = 200)
ckd_wt3[["percent.mt"]] = PercentageFeatureSet(ckd_wt3, pattern = "^mt-")

ckd_before_qc = merge(ckd_ko1, y = c(ckd_ko2, ckd_ko3, ckd_wt1, ckd_wt2, ckd_wt3),
                      add.cell.ids = c("rtn3_ko1", "rtn3_ko2", "rtn3_ko3", "rtn3_wt1", "rtn3_wt2", "rtn3_wt3"),
                      project = "CKD_mice", merge.data = TRUE)

Idents(ckd_before_qc) = factor(ckd_before_qc$orig.ident, levels = c("CKD.WT1","CKD.WT2","CKD.WT3",
                                                                    "CKD.KO1","CKD.KO2","CKD.KO3"))
```


```{r fig.height=4, fig.width=5.5}
# Vln plot visualize the data
  VlnPlot(ckd_before_qc, features = c("nCount_RNA"), ncol = 1, pt.size = 0.1) + NoLegend()
  VlnPlot(ckd_before_qc, features = c("nFeature_RNA"), ncol = 1, pt.size = 0.1) + NoLegend()
  VlnPlot(ckd_before_qc, features = c("percent.mt"), ncol = 1, pt.size = 0.1) + NoLegend()

  dim(ckd_before_qc)
  table(ckd_before_qc$orig.ident)

# save the data
  # saveRDS(ckd_before_qc, file = "../Data.freeze/1_data_preprocessing/ckd_before_qc.rds")
```

```{r}
  # [1] 57414
  length(which(ckd_before_qc$nFeature_RNA < 4000 & ckd_before_qc$nFeature_RNA > 200))
  length(which(ckd_before_qc$nCount_RNA < 40000))
  length(which(ckd_before_qc$percent.mt < 65))
  # [1] 55586
  # [1] 57128
  # [1] 49689
  
  dim(ckd_before_qc)[2]-length(which(ckd_before_qc$nFeature_RNA < 4000 & ckd_before_qc$nFeature_RNA > 200))
  dim(ckd_before_qc)[2]-length(which(ckd_before_qc$nCount_RNA < 40000))
  dim(ckd_before_qc)[2]-length(which(ckd_before_qc$percent.mt < 65))
  # [1] 1828
  # [1] 286
  # [1] 7725
  
  ckd_after_qc = subset(ckd_before_qc, subset = nFeature_RNA > 200 & nFeature_RNA < 4000 & nCount_RNA < 40000 & percent.mt < 65)
  dim(ckd_after_qc)[2]
  dim(ckd_before_qc)[2]-dim(ckd_after_qc)[2]
  # [1] 9529
  # 9529/57414
```

```{r}
# Vln plot visualize the data
  VlnPlot(ckd_after_qc, features = c("nFeature_RNA"), ncol = 1, pt.size = 0.1) + NoLegend() + ylim(c(0,max(ckd_before_qc$nFeature_RNA)))
  VlnPlot(ckd_after_qc, features = c("nCount_RNA"), ncol = 1, pt.size = 0.1) + NoLegend() + ylim(c(0,max(ckd_before_qc$nCount_RNA)))
  VlnPlot(ckd_after_qc, features = c("percent.mt"), ncol = 1, pt.size = 0.1) + NoLegend() + ylim(c(0,max(ckd_before_qc$percent.mt)))
  
# save the qc data
  saveRDS(ckd_after_qc, file = "../Data.freeze/1_data_preprocessing/ckd_after_qc.rds")
```












